program: run.py
metric:
  name: Cross-Validation Metrics Dict/weighted_score_mean
  goal: maximize

method: bayes
parameters:
  lr:
    distribution: q_log_uniform_values
    min: 1e-7
    max: 1e-4
    q: 1e-6
  eps:
    distribution: q_log_uniform_values
    min: 1e-10
    max: 1e-6
    q: 1e-10
  beta1:
    distribution: uniform
    min: 0.55
    max: 0.90
  beta2:
    distribution: uniform
    min: 0.96
    max: 0.999
  batch_size:
    values: [2,4,8,16]
  log_scale:
    values: [true, false]
  # resize:
  #   values: [true, false]

command:
- ${env}
- ${interpreter}
- ${program}
- ${args}
