program: run_final.py
metric:
  name: Test Metrics Dict/correlations/scene_mean/mos/plcc
  goal: maximize

method: bayes
parameters:
  lr:
    # value: 2e-4
    distribution: q_log_uniform_values
    min: 1e-7
    max: 1e-3
    # min: 1e-4
    # max: 1e-2
    q: 1e-8
  eps:
    # distribution: q_log_uniform_values
    # min: 1e-10
    # max: 1e-5
    # q: 1e-10
    value: 1e-7
  beta1:
    value: 0.9
    # distribution: uniform
    # min: 0.8
    # max: 0.9
  beta2:
    value: 0.999
    # distribution: uniform
    # min: 0.999
    # max: 0.99999
  # warmup_steps:
  #   value: 90
    # values: [0, 90, 180]
  epochs:
    value: 10
    # values: [10, 20, 50, 100]
  # gamma:
  #   distribution: uniform
  #   min: 0.80
  #   max: 1.0
  mode:
    # values: ['mean']
    value: 'logistic'
  project_weights:
    # values: ['True', 'False']
    value: 'False'
  optimizer:
    value: 'adam'
    # values: ['adam', 'sadamw'] #: ['nadam', 'adam', 'sgd', 'sgd_momentum']

command:
- ${env}
- ${interpreter}
- ${program}
- ${args}
